// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB41WK5WhPJcKaeTy15HSCSzFaYwxaX0LA',
    appId: '1:133960015307:web:1c6283eac120aa4e486a4e',
    messagingSenderId: '133960015307',
    projectId: 'hotelkiosk-90a6b',
    authDomain: 'hotelkiosk-90a6b.firebaseapp.com',
    storageBucket: 'hotelkiosk-90a6b.firebasestorage.app',
    measurementId: 'G-N94ZB52RQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBODXNVbkaDD0_K4RK4jHo5R1XBrm3XTGs',
    appId: '1:133960015307:android:4ba908252c5e4b49486a4e',
    messagingSenderId: '133960015307',
    projectId: 'hotelkiosk-90a6b',
    storageBucket: 'hotelkiosk-90a6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA865kD5g78dk9sc1U4nq0e3Lu73hatQA',
    appId: '1:133960015307:ios:992077061e52f029486a4e',
    messagingSenderId: '133960015307',
    projectId: 'hotelkiosk-90a6b',
    storageBucket: 'hotelkiosk-90a6b.firebasestorage.app',
    iosBundleId: 'com.example.hotelkiosk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA865kD5g78dk9sc1U4nq0e3Lu73hatQA',
    appId: '1:133960015307:ios:992077061e52f029486a4e',
    messagingSenderId: '133960015307',
    projectId: 'hotelkiosk-90a6b',
    storageBucket: 'hotelkiosk-90a6b.firebasestorage.app',
    iosBundleId: 'com.example.hotelkiosk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB41WK5WhPJcKaeTy15HSCSzFaYwxaX0LA',
    appId: '1:133960015307:web:82a45556604bbc20486a4e',
    messagingSenderId: '133960015307',
    projectId: 'hotelkiosk-90a6b',
    authDomain: 'hotelkiosk-90a6b.firebaseapp.com',
    storageBucket: 'hotelkiosk-90a6b.firebasestorage.app',
    measurementId: 'G-2KCP982BJL',
  );
}
